name: Build and Release Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
            jpackage_goal: win

          - os: windows-11-arm
            platform: windows
            arch: arm64
            jpackage_goal: win

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and package
        run: mvn -Pdist package jpackage:jpackage@${{ matrix.jpackage_goal }}

      # ---------- Package output ----------
      - name: Archive
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          Push-Location target\output\Nautilus
          tar -a -c -f ../../../nautilus-${{ github.ref_name }}-${{ matrix.platform }}-${{ matrix.arch }}.zip *
          Pop-Location

      # ---------- Upload artifacts ----------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nautilus-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            nautilus-${{ github.ref_name }}-${{ matrix.platform }}-${{ matrix.arch }}.*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            nautilus-windows-x64/nautilus-${{ github.ref_name }}-windows-x64.zip
            nautilus-windows-arm64/nautilus-${{ github.ref_name }}-windows-arm64.zip